swagger:
  doc:
    visitPath: /swagger.json
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/
